apiVersion: v1
kind: Service
metadata:
  name: {{ include "property-hub-stack.fullname" . }}-livekit
  labels:
    {{- include "property-hub-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: livekit
spec:
  type: {{ .Values.livekit.service.type }}
  ports:
    - port: {{ .Values.livekit.service.port }}
      targetPort: 7880
      protocol: TCP
      name: http
    - port: 7882
      targetPort: 7882
      protocol: UDP
      name: rtc-udp
  selector:
    {{- include "property-hub-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: livekit
