// Canonical role enum — matches Prisma UserRole enum exactly
export enum UserRole {
    CENTRAL_AUTHORITY = 'CENTRAL_AUTHORITY',
    PROPERTY_PARTNER = 'PROPERTY_PARTNER',
    BROKER = 'BROKER',
    BUYER = 'BUYER',
    CONSULTANT = 'CONSULTANT',
    GROWTH_PARTNER = 'GROWTH_PARTNER',
    LOAN_ADVISOR = 'LOAN_ADVISOR',
    VISIT_EXECUTIVE = 'VISIT_EXECUTIVE',
}
