apiVersion: v1
kind: Service
metadata:
  name: {{ include "property-hub-stack.fullname" . }}-frontend
  labels:
    {{- include "property-hub-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3101
      protocol: TCP
      name: http
  selector:
    {{- include "property-hub-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
