kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "property-hub-stack.fullname" . }}-n8n
  labels:
    {{- include "property-hub-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.n8n.persistence.size }}
  {{- if .Values.n8n.persistence.storageClass }}
  storageClassName: {{ .Values.n8n.persistence.storageClass }}
  {{- end }}
