apiVersion: v1
kind: Secret
metadata:
  name: {{ include "property-hub-stack.fullname" . }}-jitsi-secrets
  labels:
    {{- include "property-hub-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  JICOFO_COMPONENT_SECRET: {{ .Values.jitsi.secrets.jicofoComponentSecret }}
  JVB_COMPONENT_SECRET: {{ .Values.jitsi.secrets.jvbComponentSecret }}
  JWT_APP_SECRET: {{ .Values.jitsi.secrets.jwtAppSecret }}
  JICOFO_AUTH_PASSWORD: {{ .Values.jitsi.jicofo.auth.password }}
  JVB_AUTH_PASSWORD: {{ .Values.jitsi.jvb.auth.password }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "property-hub-stack.fullname" . }}-jitsi-config
  labels:
    {{- include "property-hub-stack.labels" . | nindent 4 }}
data:
  XMPP_SERVER: {{ include "property-hub-stack.fullname" . }}-jitsi-prosody
  XMPP_DOMAIN: {{ .Values.global.domain }}
  XMPP_AUTH_DOMAIN: "auth.{{ .Values.global.domain }}"
  XMPP_INTERNAL_MUC_DOMAIN: "internal-muc.{{ .Values.global.domain }}"
  PUBLIC_URL: {{ .Values.jitsi.publicUrl }}
  TZ: {{ .Values.jitsi.timeZone }}
