apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "property-hub-stack.fullname" . }}-jitsi-prosody
  labels:
    {{- include "property-hub-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: jitsi-prosody
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "property-hub-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: jitsi-prosody
  template:
    metadata:
      labels:
        {{- include "property-hub-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: jitsi-prosody
    spec:
      containers:
        - name: prosody
          image: "{{ .Values.jitsi.prosody.image }}"
          ports:
            - name: xmpp-client
              containerPort: 5222
            - name: xmpp-server
              containerPort: 5269
            - name: http
              containerPort: 5280
          envFrom:
            - configMapRef:
                name: {{ include "property-hub-stack.fullname" . }}-jitsi-config
            - secretRef:
                name: {{ include "property-hub-stack.fullname" . }}-jitsi-secrets
          env:
            - name: JICOFO_AUTH_USER
              value: {{ .Values.jitsi.jicofo.auth.user }}
            - name: JVB_AUTH_USER
              value: {{ .Values.jitsi.jvb.auth.user }}
