name: Docker Build and Publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Backend Version
        id: backend_version
        run: |
          VERSION=$(jq -r .version property-hub-backend/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.backend_version.outputs.version }}
            type=raw,value=latest

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./property-hub-backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get Frontend Version
        id: frontend_version
        run: |
          VERSION=$(jq -r .version property-hub-frontend/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.frontend_version.outputs.version }}
            type=raw,value=latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./property-hub-frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get Scraper Version
        id: scraper_version
        run: |
          VERSION=$(jq -r .version property-hub-scraper/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Scraper
        id: meta-scraper
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-scraper
          tags: |
            type=raw,value=${{ steps.scraper_version.outputs.version }}
            type=raw,value=latest

      - name: Build and push Scraper image
        uses: docker/build-push-action@v5
        with:
          context: ./property-hub-scraper
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-scraper.outputs.tags }}
          labels: ${{ steps.meta-scraper.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
